language: node_js
node_js: 10

jobs:
  include:
    - name: Integration tests
      script:
        - npm run build
        - xvfb-run npm run test
    - stage: Release tests
      name: Package install tests
      script:
        - npm run build:package
        - xvfb-run npm run test:package
      deploy:
        - prerelease: true
          provider: releases
          api_key:
            secure: 0DAf3BZYjaicIsivWmm2F4fUU1M/MUL9RMWCc1Fxu/NjDze8bpqJD8fSA77meg3acpUfIiYZQG3cJiDJ1an0MCl6BrT3I4Yz2WknJBnEW4JJGayLTNdhF4ThgRi9FvgT2zog2uqZ8KzOqTotAbTDvucYzBpsuLxGIfZ8Lg4pXWA3FJ9q3Dz7AWniaoIMtgkXzC9gHnfT7DcgpgBOf8j99LZGEmKjVGL8mCDmB/GZO3KTCs6ivsPUawZj/TRAxrfvqzLpSzdRLxobEA4rTMl9BGz4kek/wLL6pfkhjncpah/UJnTf6LAegcUkP13UaxdtSQ6Y2HPPu35JD8bZoQRD9yzpWH0y31nn7QESCnG98MoiVv9lj8XFwJZppS89vl23XSeB8KScRZbOjGXrFIcQyJcQSXjM12BxHu4LUQ3jxqJQnrWm4bgakU5RjzQ0xx86tO3yrQQKjUkzjVg8PHFon436BXBaXgZUCH80jmJ7vGVQhhJ3IbLHdjYkxXwyF7rVANXlgnx0ZgOqMDjhyKYiE9oT7yEjAUIQeZAiVl6tvbbuh7G/o/w2nJ9P7w+5QBu4fpyjxz2hdInBi2yc97A0VQZTbH2OAQvNa4qkhF7l6tDHTKDaOW9f3AcdB7aUlnBJhPGat/QKN5rvdWoqSTxujbDJ7Z34SUjUWipLM2l2E4c=
          file: perl-moose-$TRAVIS_TAG.vsix
          skip_cleanup: true
          on:
            branch: master
            tags: true
